In [1]:
import pandas as pd
import numpy as np
##Loading the complete fifa database
complete_data = pd.read_csv('complete_data_test.csv', sep=',')
for i in range(len(complete_data)):
    if complete_data['year'][i] == 2021:
        complete_data['contract_valid_until'][i] = complete_data['club_contract_valid_until'][i]

<ipython-input-1-da66d0b2843e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complete_data['contract_valid_until'][i] = complete_data['club_contract_valid_until'][i]

In [2]:
#Removing variables that are unnecessary and renaming columns.
complete_data.drop(['Unnamed: 0_x', 'Unnamed: 0', 'player_name', 'fee', 'transfer_movement', 'club_name_y', 'league_name_y', 'league_rank', 'season', 'player_url', 'id-name', 'Unnamed: 0_y', 'sofifa_id', 'short_name', 'long_name', 'age_y', 'dob', 'player_positions', 'work_rate', 'body_type', 'real_face', 'player_tags', 'player_traits', 'team_position', 'team_jersey_number', 'loaned_from', 'joined', 'nation_position', 'nation_jersey_number', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning', 'mentality_composure', 'defending_marking', 'value_eur', 'wage_eur'], axis = 1, inplace = True)
complete_data.rename(columns = {'club_name_x':'buying_club', 'age_x':'age','club_involved_name':'selling_club', 'league_name_x':'buying_league'}, inplace = True)
complete_data.drop(complete_data.iloc[:, 56:], inplace = True, axis = 1)

In [3]:
#Turning position into position_group
defenders = ['Centre-Back', 'Left-Back', 'Right-Back']
midfielders = ['Attacking Midfield', 'Defensive Midfield', 'Central Midfield', 'Right Midfield', 'Left Midfield']
attackers = ['Centre-Forward', 'Left Winger', 'Right Winger', 'Second Striker']
complete_data['position_group'] = 0
for i in range(len(complete_data)):
    if complete_data['position'][i] in defenders:
        complete_data['position_group'][i] = 'Defender'
    elif complete_data['position'][i] in midfielders:
        complete_data['position_group'][i] = 'Midfielder'
    elif complete_data['position'][i] in attackers:
        complete_data['position_group'][i] = 'Attacker'
complete_data = complete_data[complete_data["position_group"].str.contains('Midfielder') == True]

<ipython-input-3-159a2834a79c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complete_data['position_group'][i] = 'Defender'
C:\Users\gijsl\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
<ipython-input-3-159a2834a79c>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complete_data['position_group'][i] = 'Attacker'
<ipython-input-3-159a2834a79c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complete_data['position_group'][i] = 'Midfielder'

In [4]:
#Variables changed to categoric variables
complete_data['buying_club'] = pd.Categorical(complete_data['buying_club'])
complete_data['selling_club'] = pd.Categorical(complete_data['selling_club'])
complete_data['transfer_period'] = pd.Categorical(complete_data['transfer_period'])
complete_data['buying_league'] = pd.Categorical(complete_data['buying_league'])
complete_data['nationality'] = pd.Categorical(complete_data['nationality'])
complete_data['international_reputation'] = pd.Categorical(complete_data['international_reputation'])
complete_data['position'] = pd.Categorical(complete_data['position'])
complete_data['weak_foot'] = pd.Categorical(complete_data['weak_foot'])
complete_data['skill_moves'] = pd.Categorical(complete_data['skill_moves'])
complete_data['international_reputation'] = pd.Categorical(complete_data['international_reputation'])
complete_data['position_group'] = pd.Categorical(complete_data['position_group'])

In [5]:
#Taking all goalkeepers out of the data
data_without_gk = complete_data[complete_data["position"].str.contains('Goalkeeper') == False]
data_with_gk = complete_data[complete_data["position"].str.contains('Goalkeeper') == True]
data_without_gk = data_without_gk.reset_index(drop=True)
data_with_gk = data_with_gk.reset_index(drop=True)

,buying_club,age,position,selling_club,transfer_period,fee_cleaned,buying_league,year,height_cm,weight_kg,...,mentality_positioning,mentality_vision,mentality_penalties,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,position_group
0,Amiens SC,24.0,Attacking Midfield,Östersund,Summer,3.600,Ligue 1,2018,177,79,...,67,66,62,39,38,10,11,6,13,Midfielder
1,Arsenal FC,27.0,Defensive Midfield,Atlético Madrid,Summer,45.000,Premier League,2020,185,77,...,73,84,49,85,81,11,13,9,9,Midfielder
2,PSV Eindhoven,20.0,Attacking Midfield,FC Utrecht,Summer,4.280,Eredivisie,2016,178,73,...,72,69,58,47,46,7,10,15,12,Midfielder
3,LOSC Lille,19.0,Defensive Midfield,Hamburger SV,Summer,6.300,Ligue 1,2021,195,76,...,53,62,40,68,71,7,12,12,9,Midfielder
4,Paris Saint-Germain,26.0,Defensive Midfield,Sevilla FC,Summer,24.750,Ligue 1,2016,186,85,...,52,73,78,87,72,15,14,8,6,Midfielder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,Bristol City,20.0,Central Midfield,Everton U23,Winter,0.990,Championship,2017,182,70,...,48,47,44,17,17,9,8,10,6,Midfielder
1099,ACF Fiorentina,25.0,Central Midfield,Saint-Étienne,Winter,2.700,Serie A,2017,186,81,...,71,68,58,76,71,8,6,10,10,Midfielder
1100,Sheffield United,23.0,Central Midfield,Wolves,Winter,0.765,Championship,2017,186,88,...,62,67,53,60,59,6,11,9,15,Midfielder
1101,Sheffield United,25.0,Central Midfield,Southend United,Winter,0.711,Championship,2017,185,82,...,61,64,53,66,66,10,14,9,8,Midfielder
1102,SPAL 2013,20.0,Central Midfield,Juventus,Winter,1.800,Serie A,2017,183,76,...,55,64,52,55,52,11,10,14,8,Midfielder

In [6]:
#Creating the dummy variables
position_group_dummy = pd.get_dummies(data_without_gk['position_group'], prefix='position')
#2 in iloc because otherwise it would take 0 (for goalkeepers) as the base category, because of the 2 it is attacker
position_group_dummy = position_group_dummy.iloc[: , 2:]
buying_league_dummy = pd.get_dummies(data_without_gk['buying_league'], prefix='buying_league')
buying_league_dummy = buying_league_dummy.iloc[: , 1:]
nationality_dummy = pd.get_dummies(data_without_gk['nationality'], prefix='nationality')
nationality_dummy = nationality_dummy.iloc[: , 1:]
preferred_foot_dummy = pd.get_dummies(data_without_gk['preferred_foot'], prefix='preferred_foot')
preferred_foot_dummy = preferred_foot_dummy.iloc[: , 1:]
transfer_period_dummy = pd.get_dummies(data_without_gk['transfer_period'], prefix='transfer_period')
transfer_period_dummy = transfer_period_dummy.iloc[: , 1:]

#Dropping the initial values of the new dummies and the goalkeeper skills
temp = data_without_gk.drop(['position', 'release_clause_eur', 'buying_league', 'selling_club', 'buying_club', 'nationality', 'preferred_foot', 'transfer_period', 'position_group'], axis = 1)
model_data = pd.concat([temp, position_group_dummy, buying_league_dummy, nationality_dummy, preferred_foot_dummy, transfer_period_dummy], axis = 1)

In [8]:
#Number of rows with NA
model_data.isnull().any(axis=1).sum()

9

In [9]:
#Number of empty cells per column
for col in model_data:
    print(col, ':', (model_data[col].isna().sum()/len(model_data))*100)

age : 0.0
fee_cleaned : 0.0
year : 0.0
height_cm : 0.0
weight_kg : 0.0
overall : 0.0
potential : 0.0
international_reputation : 0.0
weak_foot : 0.0
skill_moves : 0.0
contract_valid_until : 0.1813236627379873
pace : 0.6346328195829556
shooting : 0.6346328195829556
passing : 0.6346328195829556
dribbling : 0.6346328195829556
defending : 0.6346328195829556
physic : 0.6346328195829556
attacking_crossing : 0.0
attacking_finishing : 0.0
attacking_heading_accuracy : 0.0
attacking_short_passing : 0.0
attacking_volleys : 0.0
skill_dribbling : 0.0
skill_curve : 0.0
skill_fk_accuracy : 0.0
skill_long_passing : 0.0
skill_ball_control : 0.0
movement_acceleration : 0.0
movement_sprint_speed : 0.0
movement_agility : 0.0
movement_reactions : 0.0
movement_balance : 0.0
power_shot_power : 0.0
power_jumping : 0.0
power_stamina : 0.0
power_strength : 0.0
power_long_shots : 0.0
mentality_aggression : 0.0
mentality_interceptions : 0.0
mentality_positioning : 0.0
mentality_vision : 0.0
mentality_penalties : 0.0
defending_standing_tackle : 0.0
defending_sliding_tackle : 0.0
goalkeeping_diving : 0.0
goalkeeping_handling : 0.0
goalkeeping_kicking : 0.0
goalkeeping_positioning : 0.0
buying_league_Championship : 0.0
buying_league_Eredivisie : 0.0
buying_league_Liga Nos : 0.0
buying_league_Ligue 1 : 0.0
buying_league_Premier League : 0.0
buying_league_Primera Division : 0.0
buying_league_Serie A : 0.0
nationality_Argentina : 0.0
nationality_Armenia : 0.0
nationality_Australia : 0.0
nationality_Austria : 0.0
nationality_Belgium : 0.0
nationality_Bosnia Herzegovina : 0.0
nationality_Brazil : 0.0
nationality_Burkina Faso : 0.0
nationality_Cameroon : 0.0
nationality_Canada : 0.0
nationality_Cape Verde : 0.0
nationality_Central African Republic : 0.0
nationality_Chile : 0.0
nationality_Colombia : 0.0
nationality_Comoros : 0.0
nationality_Congo : 0.0
nationality_Congo DR : 0.0
nationality_Croatia : 0.0
nationality_Curacao : 0.0
nationality_Czech Republic : 0.0
nationality_Côte d'Ivoire : 0.0
nationality_DR Congo : 0.0
nationality_Denmark : 0.0
nationality_Ecuador : 0.0
nationality_Egypt : 0.0
nationality_England : 0.0
nationality_Equatorial Guinea : 0.0
nationality_Finland : 0.0
nationality_France : 0.0
nationality_Gabon : 0.0
nationality_Georgia : 0.0
nationality_Germany : 0.0
nationality_Ghana : 0.0
nationality_Greece : 0.0
nationality_Grenada : 0.0
nationality_Guinea : 0.0
nationality_Guinea Bissau : 0.0
nationality_Haiti : 0.0
nationality_Hungary : 0.0
nationality_Iceland : 0.0
nationality_Iran : 0.0
nationality_Italy : 0.0
nationality_Ivory Coast : 0.0
nationality_Japan : 0.0
nationality_Kenya : 0.0
nationality_Kosovo : 0.0
nationality_Libya : 0.0
nationality_Liechtenstein : 0.0
nationality_Mali : 0.0
nationality_Mexico : 0.0
nationality_Moldova : 0.0
nationality_Montenegro : 0.0
nationality_Morocco : 0.0
nationality_Netherlands : 0.0
nationality_New Zealand : 0.0
nationality_Nigeria : 0.0
nationality_North Macedonia : 0.0
nationality_Northern Ireland : 0.0
nationality_Norway : 0.0
nationality_Paraguay : 0.0
nationality_Peru : 0.0
nationality_Poland : 0.0
nationality_Portugal : 0.0
nationality_Republic of Ireland : 0.0
nationality_Romania : 0.0
nationality_Russia : 0.0
nationality_Saint Kitts and Nevis : 0.0
nationality_Scotland : 0.0
nationality_Senegal : 0.0
nationality_Serbia : 0.0
nationality_Slovakia : 0.0
nationality_Slovenia : 0.0
nationality_South Africa : 0.0
nationality_Spain : 0.0
nationality_Sweden : 0.0
nationality_Switzerland : 0.0
nationality_Trinidad & Tobago : 0.0
nationality_Tunisia : 0.0
nationality_Turkey : 0.0
nationality_Ukraine : 0.0
nationality_United States : 0.0
nationality_Uruguay : 0.0
nationality_Venezuela : 0.0
nationality_Wales : 0.0
nationality_Zambia : 0.0
nationality_Zimbabwe : 0.0
preferred_foot_Right : 0.0
transfer_period_Winter : 0.0

In [10]:
model_data

,age,fee_cleaned,year,height_cm,weight_kg,overall,potential,international_reputation,weak_foot,skill_moves,...,nationality_Turkey,nationality_Ukraine,nationality_United States,nationality_Uruguay,nationality_Venezuela,nationality_Wales,nationality_Zambia,nationality_Zimbabwe,preferred_foot_Right,transfer_period_Winter
0,24.0,3.600,2018,177,79,72,78,1,3,3,...,0,0,0,0,0,0,0,0,1,0
1,27.0,45.000,2020,185,77,84,85,2,3,3,...,0,0,0,0,0,0,0,0,1,0
2,20.0,4.280,2016,178,73,74,83,1,3,3,...,0,0,0,0,0,0,0,0,1,0
3,19.0,6.300,2021,195,76,68,83,1,4,2,...,0,0,0,0,0,0,0,0,1,0
4,26.0,24.750,2016,186,85,84,86,3,3,2,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,20.0,0.990,2017,182,70,48,59,1,3,3,...,0,0,0,0,0,0,0,0,1,1
1099,25.0,2.700,2017,186,81,74,79,1,3,3,...,0,0,0,0,0,0,0,0,1,1
1100,23.0,0.765,2017,186,88,66,71,1,3,2,...,0,0,0,0,0,1,0,0,1,1
1101,25.0,0.711,2017,185,82,69,73,1,3,2,...,0,0,0,0,0,0,0,0,1,1
1102,20.0,1.800,2017,183,76,64,76,1,3,2,...,0,0,0,0,0,0,0,0,0,1

In [11]:
#Dropping the rows with an empty value
model_data = model_data.dropna()
model_data = model_data.reset_index(drop=True)
model_data.to_csv('midfielder_data.csv', index = False)
model_data

,age,fee_cleaned,year,height_cm,weight_kg,overall,potential,international_reputation,weak_foot,skill_moves,...,nationality_Turkey,nationality_Ukraine,nationality_United States,nationality_Uruguay,nationality_Venezuela,nationality_Wales,nationality_Zambia,nationality_Zimbabwe,preferred_foot_Right,transfer_period_Winter
0,24.0,3.600,2018,177,79,72,78,1,3,3,...,0,0,0,0,0,0,0,0,1,0
1,27.0,45.000,2020,185,77,84,85,2,3,3,...,0,0,0,0,0,0,0,0,1,0
2,20.0,4.280,2016,178,73,74,83,1,3,3,...,0,0,0,0,0,0,0,0,1,0
3,19.0,6.300,2021,195,76,68,83,1,4,2,...,0,0,0,0,0,0,0,0,1,0
4,26.0,24.750,2016,186,85,84,86,3,3,2,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089,20.0,0.990,2017,182,70,48,59,1,3,3,...,0,0,0,0,0,0,0,0,1,1
1090,25.0,2.700,2017,186,81,74,79,1,3,3,...,0,0,0,0,0,0,0,0,1,1
1091,23.0,0.765,2017,186,88,66,71,1,3,2,...,0,0,0,0,0,1,0,0,1,1
1092,25.0,0.711,2017,185,82,69,73,1,3,2,...,0,0,0,0,0,0,0,0,1,1
1093,20.0,1.800,2017,183,76,64,76,1,3,2,...,0,0,0,0,0,0,0,0,0,1